spring.application.name: rtl433-data-pipeline
spring.profiles.active: ${PROFILE:local}

spring.profiles.include: ingestion

server.port: ${SERVER_PORT:5001}

info:
  app.name: ${spring.application.name}
  app.version: ${version:project.version}
  app.profile: ${spring.profiles.active}

management:
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: health,info
  health.mongo.enabled: false

management.info:
  build.enabled: true
  env.enabled: true
  java.enabled: true
  os.enabled: true

logging.level:
  org.springframework: INFO